# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f50b570cebb6f60abf9799ae149a1a780e7182b89a4c08ff5b0f17b970e0466219f2d4167bc17c754e369f01b28a66f855c8b9a6ee3a3974c10271efaf83dec8

test:
  secret_key_base: b63c0fa2b3ea2015f3b77fcd8238115a9a759e3526f1eee0067f414ba7c6b99d07412e165a41025b878151f51a4a7afd14ef093d3b2d5a7088c658f1fbc7fd80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
